In [55]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [56]:
dataset = pd.read_csv('~/work/btc-without-date-copy-1.csv')

In [57]:
# Matrix of features
X=dataset.iloc[:, 1:6].values

In [58]:
# Matrix of dependent variables
y=dataset.iloc[:, 0].values

In [59]:
X

array([[9.10100e+03, 8.56500e+03, 8.72800e+03, 5.53039e+09, 1.51366e+11],
       [9.17700e+03, 8.84600e+03, 8.92900e+03, 6.04313e+09, 1.51316e+11],
       [9.05100e+03, 8.39000e+03, 8.91300e+03, 6.36179e+09, 1.45922e+11],
       ...,
       [1.47000e+02, 1.34000e+02, 1.39000e+02,         nan, 1.59778e+09],
       [1.47000e+02, 1.34000e+02, 1.45000e+02,         nan, 1.49116e+09],
       [1.36000e+02, 1.32000e+02, 1.34000e+02,         nan, 1.50052e+09]])

In [60]:
y

array([8939, 8937, 8620, ...,  144,  134,  135])

In [61]:
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values='NaN',strategy='mean',axis=0)
imputer.fit(X[:, 3:4])
X[:, 3:4] = imputer.transform(X[:, 3:4])

In [62]:
X[:,3]

array([5.53039000e+09, 6.04313000e+09, 6.36179000e+09, ...,
       1.10727838e+09, 1.10727838e+09, 1.10727838e+09])

In [63]:
# Split the dataset into training and test sets
from sklearn.cross_validation import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X, y, test_size=1/3, random_state=0)

In [64]:
# Feature scaling
# Minimizes the Euclidean distance is shorter preventing the higher numbers from dominating the lower numbers
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)

# Already fit to the training set so I dont need to fit to the test set
X_test = sc_X.transform(X_test)

#Same thing for y
#sc_y = StandardScaler()
#y_train = sc_y.fit_transform(y_train)

In [65]:
# Fitting Simple Linear Regression to the Training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [66]:
# Predicting the Test set results
y_pred = regressor.predict(X_test)

In [67]:
y_pred

array([  542.24387566,   763.45814331,   440.78486602,   812.09361364,
        2921.77719574,   333.64655515,   546.90423765,   324.51656055,
        7657.03672116,   643.74289923,   766.32883284,   275.26350131,
        8390.28072814,  4360.6662922 ,   534.8746412 ,   545.05588646,
         124.15220068,   146.7013559 ,   513.83597499,   558.77839957,
         285.89300548,  1003.12834352,  1140.85047789,   659.81554151,
         271.72852644,   762.40797811,   683.28168051,   308.47086693,
         110.56684284, 11481.1134314 ,  2010.76324239,   283.92089056,
        2514.60639818,   591.22871278,  4854.1165945 ,  1042.39001942,
        4191.64224349,   473.90461359, 14014.5816025 ,   408.42673198,
         261.15150896,   538.73012352,   123.71032552,   692.60574773,
         332.34001321,   304.64322904,   129.20374585,   625.98241008,
        1168.78388443,   389.94106511,   260.0065648 ,   301.96603428,
         579.66069623,   473.16315688,   405.85277839,   475.78607018,
      

In [68]:
X_train.size

5965

In [69]:
y_train.size

1193